name: Build

on:
  push:
    branches:
      - '**'

jobs:
  dotnet-test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
      - shell: bash
        run: |
          dotnet test

  docker-build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build service
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          target: service
          tags: cathal-dotnet-docker-multistage/service:latest
          platforms: linux-amd64,linux-arm64
      - name: Build web
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          target: web
          tags: cathal-dotnet-docker-multistage/web:latest
          platforms: linux-amd64,linux-arm64
